--- #YAML:1.0
name:               WWW-SPOJ
version:            0.00_01
abstract:           Extract data from Sphere Online Judge (SPOJ)
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                0
    Class::Accessor:     0
    HTML::TableExtract:  0
    LWP::UserAgent:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
