#!/usr/bin/perl

use warnings;
use strict;

use WWW::PDB;

my $seq = <<'END_SEQ';
SHHWGYGKHNGPEHWHKDFPIAKGERQSPVDIDTHTAKYDPSLKPLSVSYDQATSLRILNNGHAFNVEFDDSQDKAVLKG
GPLDGTYRLIQFHFHWGSLDGQGSEHTVDKKKYAAELHLVHWNTKYGDFGKAVQQPDGLAVLGIFLKVGSAKPGLQKVVD
END_SEQ

print WWW::PDB->blast($seq, 10.0, 'BLOSUM62', 'HTML');

print WWW::PDB->blast('2ili', 'A', 10.0, 'BLOSUM62', 'HTML');

print WWW::PDB->blast($seq, 10.0);

print WWW::PDB->blast('2ili', 'A', 10.0);

