#!/usr/bin/perl

use warnings;
use strict;

use WWW::PDB;

my $seq = q(
SHHWGYGKHNGPEHWHKDFPIAKGERQSPVDIDTHTAKYDPSLKPLSVSYDQATSLRILNNGHAFNVEFDDSQDKAVLKG
GPLDGTYRLIQFHFHWGSLDGQGSEHTVDKKKYAAELHLVHWNTKYGDFGKAVQQPDGLAVLGIFLKVGSAKPGLQKVVD
);

printf("%s\n", $_) for WWW::PDB->fasta($seq, 100);
