--- #YAML:1.0
name:               WWW-TinySong
version:            0.05
abstract:           Get free music links from tinysong.com
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    CGI:             0
    Exporter:        0
    HTML::Parser:    3
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
