--- #YAML:1.0
name:               WWW-PDB
version:            0.00_03
abstract:           Perl interface to the Protein Data Bank
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Exporter:             0
    Fcntl:                0
    File::Path:           0
    File::Spec:           0
    IO::File:             0
    IO::Uncompress::Gunzip:  0
    Net::FTP:             0
    SOAP::Lite:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
